// One presentation a frame, and no write that says what the element already
// says.
//
// A drifting frame used to ask the cheap question (carry the last picture one
// half-pixel bucket), write the answer to every leader, and then ask the
// locked cursor the same question and write that answer over it — 105 DOM
// writes a frame, 92 of them same-value, on 94 % of the frames of a reading.
// At rest it still wrote 15, all of them same-value. The picture was never in
// question; only the bill was.
//
// The golden is the whole tree the writer owns, frame by frame, generated from
// the code before this task landed. To regenerate after a DELIBERATE visible
// change:
//
//   cd packages/ui && CKNERV_CONSTELLATION_DOM_GOLDEN_WRITE=1 \
//     npx vitest run __tests__/components/hud/constellationOnePresentation.test.ts
//
// and say in the commit which frames moved and why.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { beforeEach, describe, expect, it } from 'vitest';
import {
  advanceConstellationFrame,
} from '../../../src/components/hud/cellConstellationFrame';
import {
  resetConstellationWorkStats,
  snapshotConstellationWorkStats,
} from '../../../src/derives/cellConstellation.derive';
import { resetFrameBudget } from '../../../src/nerve/frameBudget';
import {
  constellationStage,
  driftConstellation,
  generousClock,
} from '../../helpers/constellationStage';
import {
  censusConstellationWrites,
  constellationDomState,
} from '../../helpers/constellationWriteCensus';
import {
  CONSTELLATION_EDGE,
  CONSTELLATION_SAFE_TOP,
  railsForStage,
} from '../../fixtures/cellConstellationMatrix';

// jsdom installs its own `URL` and it does not resolve a relative reference
// against a `file:` base, so the path is joined by hand.
const GOLDEN_PATH = join(
  dirname(fileURLToPath(import.meta.url)), '..', '..', 'fixtures',
  'constellationDomFrames.json',
);

const NOTE = 'Generated by __tests__/components/hud/constellationOnePresentation.test.ts '
  + 'with CKNERV_CONSTELLATION_DOM_GOLDEN_WRITE=1. `frames` is one digest per frame over '
  + 'everything the frame writer owns in the DOM after that frame, ordered by element and '
  + 'property; `samples` carries the whole line for the frames worth reading by eye. The '
  + 'full set is 774 KB and says nothing a digest does not, except where it is printed.';

/** Frames whose whole line is kept: the first paint, the frame the composition
 *  stands on, the middle of the drift and the end. */
const SAMPLES: readonly number[] = [1, 2, 3, 21, 150, 300];

/** 1920×1080 under the right-hand rails, three instruments, drifting inward at
 *  0.6 px a frame — the reading the review measured, in the direction that
 *  keeps the Cell on a routable stage. */
const SCENARIO = {
  stageWidth: 1920,
  stageHeight: 1080,
  anchorX: 1920 * 0.78,
  anchorY: 1080 * 0.25,
  rate: -0.6,
  frames: 300,
} as const;

interface Golden {
  note: string;
  scenario: typeof SCENARIO;
  whole: string;
  frames: string[];
  samples: { [frame: string]: string };
}

/** Sixteen hex characters of sha256 — a collision costs 2^32 frames, and the
 *  case prints the line it actually produced when one moves. */
const digest = (value: string): string =>
  createHash('sha256').update(value).digest('hex').slice(0, 16);

function driftFrames(): string[] {
  resetFrameBudget();
  resetConstellationWorkStats();
  const stage = constellationStage(3);
  const frames: string[] = [];
  driftConstellation(stage, {
    ...SCENARIO,
    rails: railsForStage(SCENARIO.stageWidth),
    onFrame: () => { frames.push(constellationDomState(stage)); },
  });
  return frames;
}

beforeEach(() => {
  resetFrameBudget();
  resetConstellationWorkStats();
});

describe('one presentation per frame', () => {
  it('leaves the same tree on every frame of a drift', () => {
    const frames = driftFrames();
    const samples: { [frame: string]: string } = {};
    for (const frame of SAMPLES) samples[`${frame}`] = frames[frame - 1];
    if (process.env.CKNERV_CONSTELLATION_DOM_GOLDEN_WRITE === '1') {
      writeFileSync(GOLDEN_PATH, `${JSON.stringify({
        note: NOTE,
        scenario: SCENARIO,
        whole: digest(frames.join('\n')),
        frames: frames.map(digest),
        samples,
      }, null, 2)}\n`);
      expect(frames.length).toBe(SCENARIO.frames);
      return;
    }
    const golden = JSON.parse(readFileSync(GOLDEN_PATH, 'utf8')) as Golden;
    expect(golden.scenario, 'the scenario itself moved').toEqual(SCENARIO);
    expect(frames.length).toBe(golden.frames.length);
    // The sampled frames first: when one of them moved, the failure is the
    // whole line and says what moved rather than that something did.
    for (const frame of SAMPLES) {
      expect(samples[`${frame}`], `frame ${frame} of the drift`)
        .toBe(golden.samples[`${frame}`]);
    }
    for (let index = 0; index < frames.length; index += 1) {
      expect(digest(frames[index]),
        `frame ${index + 1} of the drift moved; it now reads\n${frames[index]}`)
        .toBe(golden.frames[index]);
    }
    expect(digest(frames.join('\n'))).toBe(golden.whole);
  }, 120000);

  it('writes twenty times or fewer on a drifting frame, and never twice for one answer', () => {
    const stage = constellationStage(3);
    const census = censusConstellationWrites(stage);
    const perFrame: number[] = [];
    let same = 0;
    // A frame over the bar is only honest if the PICTURE changed beyond its
    // leaders' geometry: a plate that started travelling to a new seat takes
    // the leaders down and gives them back, a cut set that gained a rectangle
    // is a different mask, and a refinement landing is a second and better
    // answer rather than the same one twice. Anything else over the bar is a
    // frame presenting one answer two ways.
    const overTheBar: string[] = [];
    let refineLandings = 0;
    driftConstellation(stage, {
      ...SCENARIO,
      rails: railsForStage(SCENARIO.stageWidth),
      onFrame: (frame) => {
        // The first frames are a first paint: the composition is being solved
        // and the plates arrive. The bill this case is about is the steady one.
        const landings = snapshotConstellationWorkStats().refineLandings;
        const refined = landings !== refineLandings;
        refineLandings = landings;
        if (frame > 20) {
          const total = census.total();
          perFrame.push(total);
          same += census.same;
          const keys = Object.keys(census.byKey);
          if (total > 20) {
            const changedThePicture = refined || keys.some((key) =>
              key.endsWith('.host.$transform') || key.endsWith('.host.$visibility')
              || key === 'masks.replaceChildren');
            overTheBar.push(`frame ${frame}: ${total} writes`);
            expect(changedThePicture,
              `frame ${frame} wrote ${total} times and changed nothing but its leaders: `
              + JSON.stringify(census.byKey)).toBe(true);
          }
        }
        census.reset();
      },
    });
    const sorted = [...perFrame].sort((a, b) => a - b);
    const at = (share: number) => sorted[Math.floor(sorted.length * share)];
    expect(perFrame.length).toBeGreaterThan(250);
    expect(at(0.5), `median writes a drifting frame: ${at(0.5)}`).toBeLessThanOrEqual(20);
    expect(at(0.95), `p95 writes a drifting frame: ${at(0.95)}`).toBeLessThanOrEqual(20);
    expect(same, `same-value writes over ${perFrame.length} drifting frames`).toBe(0);
    expect(overTheBar.length, overTheBar.join('; ')).toBeLessThanOrEqual(3);
  }, 120000);

  it('writes nothing at all on a settled frame', () => {
    const stage = constellationStage(3);
    const now = generousClock();
    const rails = railsForStage(1920);
    const frame = (serial: number) => advanceConstellationFrame(
      stage.handles, 1920 * 0.5, 1080 * 0.5, 1920, 1080,
      CONSTELLATION_SAFE_TOP, CONSTELLATION_EDGE, rails, 0, serial, now,
    );
    for (let serial = 1; serial <= 60; serial += 1) frame(serial);
    const census = censusConstellationWrites(stage);
    for (let serial = 61; serial <= 360; serial += 1) frame(serial);
    expect(census.same, `same-value writes at rest: ${JSON.stringify(census.byKey)}`).toBe(0);
    expect(census.changed, `changed writes at rest: ${JSON.stringify(census.byKey)}`).toBe(0);
  }, 120000);

  it('cuts the chip out of the mask in place while the seats stand', () => {
    const stage = constellationStage(3);
    const census = censusConstellationWrites(stage);
    const group = stage.handles.maskGroup as SVGGElement;
    let cutWrites = 0;
    let rebuiltTheSameSet = 0;
    let rebuiltADifferentSet = 0;
    let cuts = 0;
    const observer = new MutationObserver(() => {});
    observer.observe(group, {
      subtree: true, attributes: true, attributeFilter: ['x', 'y', 'width', 'height'],
    });
    driftConstellation(stage, {
      ...SCENARIO,
      rails: railsForStage(SCENARIO.stageWidth),
      onFrame: (frame) => {
        cutWrites += observer.takeRecords().length;
        const rebuilt = (census.byKey['masks.replaceChildren']?.[0] ?? 0) > 0;
        const now = group.childElementCount;
        // Frame 20 is past the first paint: from here the composition stands
        // and every cut but the chip's is a fact about the seats.
        if (frame === 20) cutWrites = 0;
        if (frame > 20 && rebuilt) {
          if (now === cuts) rebuiltTheSameSet += 1; else rebuiltADifferentSet += 1;
        }
        cuts = now;
        census.reset();
      },
    });
    observer.disconnect();
    expect(cuts).toBeGreaterThan(0);
    expect(cutWrites, 'the chip cut was never updated in place').toBeGreaterThan(0);
    // A cut set that gained or lost a rectangle IS a different set and is
    // built again; the chip tracking the Cell through the same set is not.
    expect(rebuiltTheSameSet,
      `${rebuiltTheSameSet} mask rebuilds for the same set of cuts`).toBe(0);
    expect(rebuiltADifferentSet).toBeLessThanOrEqual(2);
  }, 120000);

  it('shows the cheap answer only when the real one is not coming this frame', () => {
    // The locked cursor lands on 94 % of drifting frames. On those the
    // provisional presentation was written and then overwritten inside the
    // same slice; now it is not written at all.
    const stage = constellationStage(3);
    let framesWithBoth = 0;
    let landings = 0;
    driftConstellation(stage, {
      ...SCENARIO,
      rails: railsForStage(SCENARIO.stageWidth),
      onFrame: (frame) => {
        if (frame <= 20) return;
        // `provisionalVisible` is the writer's own record of having shown the
        // carried picture; a landing clears it, so a frame that did both ends
        // with `presentationDirty` false and a provisional frame counted.
        if (stage.handles.provisionalVisible) framesWithBoth += 1;
        else landings += 1;
      },
    });
    expect(landings).toBeGreaterThan(250);
    expect(framesWithBoth).toBe(0);
  }, 120000);
});
