import { useEffect } from 'react';

/**
 * What the HUD covers, in viewport coordinates, for the surfaces that have to
 * compose around it.
 *
 * Three scene consumers already read `[data-hud-occlusion="true"]` on their own
 * cadence — the memory markers at 250 ms, the causal lens per lens rebuild, the
 * route camera per shot. Each of them wants the rects in a different space
 * (canvas-local, render-target-scaled) and can afford to trail, so each keeps
 * its own reader. This module exists for the one consumer that cannot: the
 * inspector placement solver runs inside the frame loop, must not force a
 * layout pass there, and must not allocate. So the measurement is hoisted out
 * of the frame entirely — taken on the three events that can actually move a
 * panel, coalesced through one animation frame, and published as ONE array
 * mutated in place, so a card holding it holds a reference that is always
 * current and never new.
 */

export interface HudOcclusionRect {
  left: number;
  top: number;
  right: number;
  bottom: number;
}

/**
 * The published rects. Mutated in place and never reallocated: the frame loop
 * reads this array on every frame a card is open, and a fresh array per
 * measurement would be garbage generated by the HUD's own resize handler.
 */
const rects: HudOcclusionRect[] = [];

/** Live consumers. The listeners and the loop exist only while a card does. */
let retainCount = 0;
let framePending: number | null = null;

/**
 * Read every HUD occluder that the inspector must compose around.
 *
 * ⚠️ The exclusion is not an optimisation. `ConsensusMemoryTracePlate` carries
 * `data-hud-occlusion="true"` and it renders INSIDE the cell card — it is a
 * genuine occluder of the scene behind it, which is why it has the attribute,
 * and it travels with the card. A solver that took it as an obstacle would
 * push the card away from a rect that moves with the card: the card would run
 * off the screen chasing its own contents. So anything inside an inspection
 * layer is not an obstacle to inspection.
 */
function measureNow(): void {
  if (typeof document === 'undefined') {
    rects.length = 0;
    return;
  }
  const elements = document.querySelectorAll<HTMLElement>(
    '[data-hud-occlusion="true"]',
  );
  const width = typeof window === 'undefined' ? 0 : window.innerWidth;
  const height = typeof window === 'undefined' ? 0 : window.innerHeight;
  let kept = 0;
  for (let index = 0; index < elements.length; index += 1) {
    const element = elements[index];
    if (element.closest('[data-scene-inspection-layer]')) continue;
    const box = element.getBoundingClientRect();
    // Clipped to the viewport, the way the route camera clips: a panel that
    // has scrolled half off screen only occludes the half that is on it.
    const left = Math.max(0, box.left);
    const top = Math.max(0, box.top);
    const right = width > 0 ? Math.min(width, box.right) : box.right;
    const bottom = height > 0 ? Math.min(height, box.bottom) : box.bottom;
    if (right <= left || bottom <= top) continue;
    const slot = rects[kept];
    if (slot) {
      slot.left = left;
      slot.top = top;
      slot.right = right;
      slot.bottom = bottom;
    } else {
      rects.push({ left, top, right, bottom });
    }
    kept += 1;
  }
  rects.length = kept;
}

/**
 * One measurement per animation frame, whatever asked for it. A resize drag
 * fires `resize` dozens of times a second and a panel toggle lands in the same
 * commit as the layout it changes; both want exactly one forced layout, after
 * the browser has finished the one it was going to do anyway.
 */
function scheduleMeasure(): void {
  if (typeof requestAnimationFrame === 'undefined') {
    measureNow();
    return;
  }
  if (framePending !== null) return;
  framePending = requestAnimationFrame(() => {
    framePending = null;
    measureNow();
  });
}

/**
 * Tell the reader the HUD's own layout changed — a panel toggled, a rail
 * collapsed, a banner claimed the top slot. The events below catch the
 * viewport moving; nothing in the DOM announces a React commit, so the HUD
 * says so itself rather than being polled for it.
 */
export function invalidateHudOcclusionRects(): void {
  if (retainCount === 0) return;
  scheduleMeasure();
}

function onViewportChange(): void {
  scheduleMeasure();
}

function retain(): () => void {
  retainCount += 1;
  if (retainCount === 1 && typeof window !== 'undefined') {
    window.addEventListener('resize', onViewportChange);
    document.addEventListener('visibilitychange', onViewportChange);
  }
  // Synchronous, not scheduled: a card that just opened places on its very
  // first frame, and a frame's worth of empty obstacles is a card that lands
  // on a rail and then jumps off it.
  measureNow();
  return () => {
    retainCount -= 1;
    if (retainCount > 0) return;
    if (typeof window !== 'undefined') {
      window.removeEventListener('resize', onViewportChange);
      document.removeEventListener('visibilitychange', onViewportChange);
    }
    if (framePending !== null && typeof cancelAnimationFrame !== 'undefined') {
      cancelAnimationFrame(framePending);
    }
    framePending = null;
    rects.length = 0;
  };
}

/**
 * The HUD's occluding rects, for a surface that composes around them.
 *
 * The returned array is the module's own and never changes identity, so it is
 * safe as a prop into a component that reads it in a frame loop: there is no
 * re-render on a measurement, and no stale copy either. Mounting is what keeps
 * the measurement alive — with no inspector open, nothing measures at all.
 */
export function useHudOcclusionRects(): readonly HudOcclusionRect[] {
  useEffect(() => retain(), []);
  return rects;
}

/** How often the dim below re-reads where the transparent window is. The
 *  square travels with the card and the card travels with the galaxy's own
 *  slow turn, so a panel gives way a quarter-second after the window reaches
 *  it — the cadence `ConsensusMemoryMarkers` already reads these same rects at,
 *  and the same reasoning: a decision about which panel is in the way may
 *  trail the frame; it may not force a layout inside it. */
export const HUD_DIM_SAMPLE_MS = 250;

/** Panels currently standing under a transparent card window. Held so the mark
 *  can be lifted from exactly what it was put on — a panel that has since been
 *  toggled off is gone from the DOM and needs no un-marking, and a panel the
 *  window has left must not keep a mark somebody else's query would find. */
const dimmed = new Set<HTMLElement>();

/**
 * Give way under a transparent window.
 *
 * The CELL SCAN square is a hole in the card: the braid is painted in the
 * SCENE, beneath the whole DOM HUD, so any panel between the canvas and the
 * card prints through it and reads as text tattooed across the specimen. The
 * placement solver keeps the card — square included — off the panels wherever
 * the stage has room for that. Where it has not (a 1,000 px stage has no hole
 * at all between the rails) something has to give, and it is the panel: a
 * summary at a quarter of its light is still legible as a panel, while a
 * specimen with a chain tip written across it is not a specimen.
 *
 * `null` lifts every mark, which is what a closing card owes the HUD.
 */
export function dimHudPanelsUnder(window_: HudOcclusionRect | null): number {
  if (typeof document === 'undefined') return 0;
  const stale = dimmed;
  const next = new Set<HTMLElement>();
  if (window_) {
    const elements = document.querySelectorAll<HTMLElement>(
      '[data-hud-occlusion="true"]',
    );
    for (let index = 0; index < elements.length; index += 1) {
      const element = elements[index];
      if (element.closest('[data-scene-inspection-layer]')) continue;
      const box = element.getBoundingClientRect();
      const overlaps = window_.left < box.right
        && window_.right > box.left
        && window_.top < box.bottom
        && window_.bottom > box.top;
      if (!overlaps) continue;
      next.add(element);
      if (element.dataset.hudDim !== 'true') element.dataset.hudDim = 'true';
    }
  }
  stale.forEach((element) => {
    if (next.has(element)) return;
    delete element.dataset.hudDim;
  });
  dimmed.clear();
  next.forEach((element) => dimmed.add(element));
  return dimmed.size;
}

/** Test seam: measure now, synchronously, without mounting a component. */
export function measureHudOcclusionRectsForTest(): readonly HudOcclusionRect[] {
  measureNow();
  return rects;
}
