import { useEffect, useSyncExternalStore } from 'react';

/**
 * What the HUD covers, in viewport coordinates, for the surfaces that have to
 * compose around it.
 *
 * Three scene consumers already read `[data-hud-occlusion="true"]` on their own
 * cadence — the memory markers at 250 ms, the causal lens per lens rebuild, the
 * route camera per shot. Each of them wants the rects in a different space
 * (canvas-local, render-target-scaled) and can afford to trail, so each keeps
 * its own reader. This module exists for the one consumer that cannot: the
 * inspector placement solver runs inside the frame loop, must not force a
 * layout pass there, and must not allocate. So the measurement is hoisted out
 * of the frame entirely — taken on the three events that can actually move a
 * panel, coalesced through one animation frame, and published as ONE array
 * mutated in place, so a card holding it holds a reference that is always
 * current and never new.
 */

export interface HudOcclusionRect {
  left: number;
  top: number;
  right: number;
  bottom: number;
}

/** The clear stage between whatever the HUD stands on the left and whatever it
 *  stands on the right, in viewport px. */
export interface HudHole {
  left: number;
  right: number;
}

/**
 * The published rects. Mutated in place and never reallocated: the frame loop
 * reads this array on every frame a card is open, and a fresh array per
 * measurement would be garbage generated by the HUD's own resize handler.
 */
const rects: HudOcclusionRect[] = [];
let rectVersion = 0;

/** Live consumers. The listeners and the loop exist only while a card does. */
let retainCount = 0;
let framePending: number | null = null;

/**
 * Read every HUD occluder that the inspector must compose around.
 *
 * ⚠️ The exclusion is not an optimisation. `ConsensusMemoryTracePlate` carries
 * `data-hud-occlusion="true"` and it renders INSIDE the cell card — it is a
 * genuine occluder of the scene behind it, which is why it has the attribute,
 * and it travels with the card. A solver that took it as an obstacle would
 * push the card away from a rect that moves with the card: the card would run
 * off the screen chasing its own contents. So anything inside an inspection
 * layer is not an obstacle to inspection.
 */
function measureNow(): void {
  if (typeof document === 'undefined') {
    rects.length = 0;
    publishHoleWidth();
    return;
  }
  const elements = document.querySelectorAll<HTMLElement>(
    '[data-hud-occlusion="true"]',
  );
  const width = typeof window === 'undefined' ? 0 : window.innerWidth;
  const height = typeof window === 'undefined' ? 0 : window.innerHeight;
  let kept = 0;
  let changed = false;
  for (let index = 0; index < elements.length; index += 1) {
    const element = elements[index];
    if (element.closest('[data-scene-inspection-layer]')) continue;
    const box = element.getBoundingClientRect();
    // Clipped to the viewport, the way the route camera clips: a panel that
    // has scrolled half off screen only occludes the half that is on it.
    const left = Math.max(0, box.left);
    const top = Math.max(0, box.top);
    const right = width > 0 ? Math.min(width, box.right) : box.right;
    const bottom = height > 0 ? Math.min(height, box.bottom) : box.bottom;
    if (right <= left || bottom <= top) continue;
    const slot = rects[kept];
    if (slot) {
      changed = changed || slot.left !== left || slot.top !== top
        || slot.right !== right || slot.bottom !== bottom;
      slot.left = left;
      slot.top = top;
      slot.right = right;
      slot.bottom = bottom;
    } else {
      rects.push({ left, top, right, bottom });
      changed = true;
    }
    kept += 1;
  }
  if (rects.length !== kept) changed = true;
  rects.length = kept;
  if (changed) rectVersion += 1;
  publishHoleWidth();
}

/** Monotonic geometry version. The rect array intentionally keeps its identity,
 * so frame writers use this value to invalidate a held layout after an in-place
 * HUD measurement update. */
export function hudOcclusionVersion(): number {
  return rectVersion;
}

/**
 * The hole the HUD leaves the stage, from the panel boxes it publishes.
 *
 * Inspection uses the current obstacles to place and size its cards. The
 * overview camera instead reads `useHudCameraFrame`'s stable rail reservation:
 * a panel growing or moving out of this band must not reframe the scene.
 *
 * A panel counts only if it crosses the stage's own middle band — the rows the
 * galaxy is actually drawn in, and the rows a tethered card sits in. The
 * status strip spans the whole width at the top and is not a wall the
 * composition has to fit between; the rails are.
 */
export function hudHoleFromRects(
  rects_: readonly HudOcclusionRect[],
  viewportWidth: number,
  viewportHeight: number,
): HudHole {
  const bandTop = viewportHeight * 0.3;
  const bandBottom = viewportHeight * 0.7;
  let left = 0;
  let right = viewportWidth;
  for (let index = 0; index < rects_.length; index += 1) {
    const rect = rects_[index];
    if (rect.top >= bandBottom || rect.bottom <= bandTop) continue;
    const middle = (rect.left + rect.right) / 2;
    if (middle < viewportWidth / 2) {
      if (rect.right > left) left = rect.right;
    } else if (rect.left < right) {
      right = rect.left;
    }
  }
  return { left, right: Math.max(left, right) };
}

/**
 * The hole's width, published as a store rather than returned from a
 * measurement.
 *
 * The rects array above is deliberately mutated in place and never notifies:
 * its consumer is a frame loop, which reads it every frame anyway. A card's
 * COMPOSITION is the opposite kind of consumer — it is a render, it happens
 * when React says so, and it has to change when a rail collapses or a window
 * is dragged. So the width alone is a `useSyncExternalStore` value: it changes
 * rarely, it is one number, and a card can be re-rendered by it without the
 * frame loop paying anything.
 */
let publishedHoleWidth = 0;
const holeListeners = new Set<() => void>();

function publishHoleWidth(): void {
  const width = typeof window === 'undefined' ? 0 : window.innerWidth;
  const height = typeof window === 'undefined' ? 0 : window.innerHeight;
  const hole = hudHoleFromRects(rects, width, height);
  const next = Math.max(0, hole.right - hole.left);
  if (next === publishedHoleWidth) return;
  publishedHoleWidth = next;
  holeListeners.forEach((listener) => listener());
}

/**
 * ⚠️ Measures during a render when nothing else is watching.
 *
 * A card's first paint has to be in the composition it is going to stay in: a
 * card that opens 856 wide and snaps to 728 a frame later is the jump this
 * whole round exists to remove. The rects are measured in an effect, which
 * runs after that first paint, so the first read takes the measurement itself.
 * It is a `getBoundingClientRect` over the HUD's half-dozen panels, once per
 * card, and it is the same reading the effect would have taken — while a card
 * is open `retainCount` is at least its own, and this branch is dead.
 */
function readHoleWidth(): number {
  if (retainCount === 0) measureNow();
  return publishedHoleWidth;
}

function subscribeHoleWidth(listener: () => void): () => void {
  holeListeners.add(listener);
  return () => { holeListeners.delete(listener); };
}

/**
 * How much clear stage the HUD leaves, for a surface that changes shape with
 * it. Re-renders its caller when — and only when — the number changes.
 */
export function useHudHoleWidth(): number {
  // Retaining is what keeps the measurement alive; the store carries the
  // answer. The order matters only in that both are hooks: React runs the
  // retain first, and the store's own subscribe re-reads after it.
  useEffect(() => retain(), []);
  return useSyncExternalStore(subscribeHoleWidth, readHoleWidth, readHoleWidth);
}

/**
 * One measurement per animation frame, whatever asked for it. A resize drag
 * fires `resize` dozens of times a second and a panel toggle lands in the same
 * commit as the layout it changes; both want exactly one forced layout, after
 * the browser has finished the one it was going to do anyway.
 */
function scheduleMeasure(): void {
  if (typeof requestAnimationFrame === 'undefined') {
    measureNow();
    return;
  }
  if (framePending !== null) return;
  framePending = requestAnimationFrame(() => {
    framePending = null;
    measureNow();
  });
}

/**
 * Tell the reader the HUD's own layout changed — a panel toggled, a rail
 * collapsed, a banner claimed the top slot. The events below catch the
 * viewport moving; nothing in the DOM announces a React commit, so the HUD
 * says so itself rather than being polled for it.
 */
export function invalidateHudOcclusionRects(): void {
  if (retainCount === 0) return;
  scheduleMeasure();
}

function onViewportChange(): void {
  scheduleMeasure();
}

function retain(): () => void {
  retainCount += 1;
  if (retainCount === 1 && typeof window !== 'undefined') {
    window.addEventListener('resize', onViewportChange);
    document.addEventListener('visibilitychange', onViewportChange);
  }
  // Synchronous, not scheduled: a card that just opened places on its very
  // first frame, and a frame's worth of empty obstacles is a card that lands
  // on a rail and then jumps off it.
  measureNow();
  return () => {
    retainCount -= 1;
    if (retainCount > 0) return;
    if (typeof window !== 'undefined') {
      window.removeEventListener('resize', onViewportChange);
      document.removeEventListener('visibilitychange', onViewportChange);
    }
    if (framePending !== null && typeof cancelAnimationFrame !== 'undefined') {
      cancelAnimationFrame(framePending);
    }
    framePending = null;
    rects.length = 0;
  };
}

/**
 * The HUD's occluding rects, for a surface that composes around them.
 *
 * The returned array is the module's own and never changes identity, so it is
 * safe as a prop into a component that reads it in a frame loop: there is no
 * re-render on a measurement, and no stale copy either. Mounting is what keeps
 * the measurement alive — with no inspector open, nothing measures at all.
 */
export function useHudOcclusionRects(): readonly HudOcclusionRect[] {
  useEffect(() => retain(), []);
  return rects;
}

/** How often the dim below re-reads where the card is. The card travels with
 *  the galaxy's own slow turn, so a panel gives way a quarter-second after the
 *  card reaches it — the cadence `ConsensusMemoryMarkers` already reads these same rects at,
 *  and the same reasoning: a decision about which panel is in the way may
 *  trail the frame; it may not force a layout inside it. */
export const HUD_DIM_SAMPLE_MS = 250;

/** Panels currently standing under a card. Held so the mark can be lifted from
 *  exactly what it was put on — a panel that has since been toggled off is
 *  gone from the DOM and needs no un-marking, and a panel the card has left
 *  must not keep a mark somebody else's query would find. */
const dimmed = new Set<HTMLElement>();

/**
 * Give way under a card.
 *
 * The placement solver keeps the card off the panels wherever the stage has
 * room for that, so this is the fallback for the two cases it cannot answer,
 * and the CALLER decides which box it is holding (`CellInspectionOverlay`):
 *
 *   the CELL SCAN square, which is a hole in the card — the braid is painted
 *   in the SCENE, beneath the whole DOM HUD, so any panel between the canvas
 *   and the card prints through it and reads as text tattooed across the
 *   specimen;
 *
 *   the whole card, when the stage is narrower than the card's own floor and
 *   the card lands on the rails whatever the solver does with it.
 *
 * Either way it is the panel that gives way, and for the same reason: a
 * summary at a quarter of its light is still legible as a panel, while a
 * specimen with a chain tip written across it is not a specimen and a summary
 * with a card's edge through it is not a summary.
 *
 * `null` lifts every mark, which is what a closing card owes the HUD.
 */
export function dimHudPanelsUnder(
  standing: HudOcclusionRect | readonly HudOcclusionRect[] | null,
): number {
  if (typeof document === 'undefined') return 0;
  const stale = dimmed;
  const next = new Set<HTMLElement>();
  // One box or several. The cell dialect stands three or four instruments on
  // the stage instead of one card, and a rail owes its light to whichever of
  // them is actually on it — a union rectangle would dim rails that nothing
  // covers, which is a panel standing aside for no one.
  const boxes: readonly HudOcclusionRect[] = standing === null
    ? []
    : (Array.isArray(standing) ? standing : [standing as HudOcclusionRect]);
  if (boxes.length > 0) {
    const elements = document.querySelectorAll<HTMLElement>(
      '[data-hud-occlusion="true"]',
    );
    for (let index = 0; index < elements.length; index += 1) {
      const element = elements[index];
      if (element.closest('[data-scene-inspection-layer]')) continue;
      const box = element.getBoundingClientRect();
      let overlaps = false;
      for (const claim of boxes) {
        if (claim.left < box.right && claim.right > box.left
          && claim.top < box.bottom && claim.bottom > box.top) { overlaps = true; break; }
      }
      if (!overlaps) continue;
      next.add(element);
      if (element.dataset.hudDim !== 'true') element.dataset.hudDim = 'true';
    }
  }
  stale.forEach((element) => {
    if (next.has(element)) return;
    delete element.dataset.hudDim;
  });
  dimmed.clear();
  next.forEach((element) => dimmed.add(element));
  return dimmed.size;
}

/** Test seam: measure now, synchronously, without mounting a component. */
export function measureHudOcclusionRectsForTest(): readonly HudOcclusionRect[] {
  measureNow();
  return rects;
}
