// The oracle.
//
// Every later repair phase has to prove it did not move a plate, a leader, a
// label or a mask cut that nobody asked it to move. "No collision" is not that
// proof: a layout can satisfy every invariant the suites assert and still be a
// different picture. This file freezes the whole answer — status, template,
// every placement, every route point, every label box and every mask rectangle
// — for the 162 inputs of `cellConstellationMatrix.ts`, and asserts it back
// byte for byte.
//
// Only the CLEAN cases are asserted: a case whose status is not `unavailable`
// and whose placements all carry a route that is not degraded. The rest are
// listed with `"clean": false` and are exempt, because they are exactly the
// cases the repair is meant to change.
//
// To regenerate after a deliberate visible change:
//
//   cd packages/ui && CKNERV_CONSTELLATION_ORACLE_WRITE=1 \
//     npx vitest run __tests__/derives/cellConstellation.oracle.test.ts
//
// and commit the fixture on its own, with a message saying which cases moved
// and why.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  constellationLayout,
  type ConstellationLayout,
} from '../../src/derives/cellConstellation.derive';
import {
  CONSTELLATION_EDGE,
  CONSTELLATION_SAFE_TOP,
  constellationMatrixCases,
  constellationMatrixInput,
} from '../fixtures/cellConstellationMatrix';

// jsdom installs its own `URL` global and it does not resolve a relative
// reference against a `file:` base, so the path is joined by hand.
const FIXTURE_PATH = join(
  dirname(fileURLToPath(import.meta.url)), '..', 'fixtures', 'cellConstellationOracle.json',
);

interface OraclePoint { x: number; y: number }
interface OracleLabel {
  x: number; y: number; width: number; height: number; inPanel: boolean;
}
interface OracleRoute { points: OraclePoint[]; label: OracleLabel }
interface OraclePlacement {
  slot: string;
  quadrant: string;
  x: number; y: number; width: number; height: number;
  capped: boolean;
  route: OracleRoute | null;
}
interface OracleRect { left: number; top: number; right: number; bottom: number }
interface OracleLayout {
  status: string;
  template: string | null;
  placements: OraclePlacement[];
  masks: OracleRect[];
}
interface OracleInput {
  stageWidth: number; stageHeight: number;
  anchorX: number; anchorY: number;
  panels: number;
  rails: number;
  safeTop: number; edge: number;
  reserved: OracleRect[];
}
interface OracleCase {
  key: string;
  clean: boolean;
  input: OracleInput;
  layout: OracleLayout;
}
interface OracleFixture { note: string; cases: OracleCase[] }

const NOTE = 'Generated by __tests__/derives/cellConstellation.oracle.test.ts with '
  + 'CKNERV_CONSTELLATION_ORACLE_WRITE=1. Clean cases are asserted byte for byte; '
  + 'cases marked "clean": false are exempt.';

const rect = (box: {
  left: number; top: number; right: number; bottom: number;
}): OracleRect => ({ left: box.left, top: box.top, right: box.right, bottom: box.bottom });

/** Exactly the fields the writer puts on the screen. `route.degraded` and
 * `layout.leaders` are deliberately NOT recorded: they are properties of how
 * the answer was reached, and adding them must not move the picture. */
function projectLayout(layout: ConstellationLayout): OracleLayout {
  return {
    status: layout.status,
    template: layout.template,
    placements: layout.placements.map((placement) => ({
      slot: placement.slot,
      quadrant: placement.quadrant,
      x: placement.x,
      y: placement.y,
      width: placement.width,
      height: placement.height,
      capped: placement.capped,
      route: placement.route
        ? {
          points: placement.route.points.map((point) => ({ x: point.x, y: point.y })),
          label: {
            x: placement.route.label.x,
            y: placement.route.label.y,
            width: placement.route.label.width,
            height: placement.route.label.height,
            inPanel: placement.route.label.inPanel,
          },
        }
        : null,
    })),
    masks: layout.masks.map(rect),
  };
}

/** A case is clean when every instrument it seats is reachable by a route the
 * canonical router itself found. A degraded leader — the straight fallback —
 * is honest, but it is not the picture this oracle is holding still. */
function isClean(layout: ConstellationLayout): boolean {
  return layout.status !== 'unavailable'
    && layout.placements.length > 0
    && layout.placements.every((placement) => placement.route
      && !(placement.route as { degraded?: boolean }).degraded);
}

function buildOracle(): OracleFixture {
  const cases: OracleCase[] = [];
  for (const matrixCase of constellationMatrixCases()) {
    const layout = constellationLayout(constellationMatrixInput(matrixCase));
    cases.push({
      key: matrixCase.key,
      clean: isClean(layout),
      input: {
        stageWidth: matrixCase.stageWidth,
        stageHeight: matrixCase.stageHeight,
        anchorX: matrixCase.anchorX,
        anchorY: matrixCase.anchorY,
        panels: matrixCase.count,
        rails: matrixCase.obstacles.length,
        safeTop: CONSTELLATION_SAFE_TOP,
        edge: CONSTELLATION_EDGE,
        reserved: matrixCase.reserved.map(rect),
      },
      layout: projectLayout(layout),
    });
  }
  return { note: NOTE, cases };
}

const serialize = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`;

describe('the cell constellation oracle', () => {
  it('reproduces every clean layout byte for byte', () => {
    const actual = buildOracle();
    if (process.env.CKNERV_CONSTELLATION_ORACLE_WRITE === '1') {
      writeFileSync(FIXTURE_PATH, serialize(actual));
      // A regeneration run is a write, not a verdict. The assertion below is
      // what the suite means; this branch only refuses to pretend otherwise.
      expect(actual.cases.length).toBeGreaterThan(0);
      return;
    }
    const expected = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8')) as OracleFixture;
    expect(actual.cases.map((item) => item.key)).toEqual(expected.cases.map((item) => item.key));

    const recorded = new Map(expected.cases.map((item) => [item.key, item]));
    let asserted = 0;
    for (const item of actual.cases) {
      const oracle = recorded.get(item.key);
      expect(oracle, `no oracle case for ${item.key}`).toBeDefined();
      expect(serialize(item.input), `${item.key}: the inputs themselves moved`)
        .toBe(serialize(oracle!.input));
      if (!oracle!.clean) continue;
      asserted += 1;
      expect(item.clean, `${item.key}: a clean layout lost a canonical route`).toBe(true);
      expect(serialize(item.layout), `${item.key}: the layout moved`)
        .toBe(serialize(oracle!.layout));
    }
    expect(asserted).toBeGreaterThan(100);
  });
});
