// The oracle.
//
// Every later repair phase has to prove it did not move a plate, a leader, a
// label or a mask cut that nobody asked it to move. "No collision" is not that
// proof: a layout can satisfy every invariant the suites assert and still be a
// different picture. This file freezes the whole answer — status, template,
// every placement, every route point, every label box and every mask rectangle
// — for the 162 inputs of `cellConstellationMatrix.ts`, and asserts it back
// byte for byte.
//
// Only the CLEAN cases are asserted: a case whose status is not `unavailable`
// and whose placements all carry a route that is not degraded. The rest are
// listed with `"clean": false` and are exempt, because they are exactly the
// cases the repair is meant to change.
//
// To regenerate after a deliberate visible change:
//
//   cd packages/ui && CKNERV_CONSTELLATION_ORACLE_WRITE=1 \
//     npx vitest run __tests__/derives/cellConstellation.oracle.test.ts
//
// and commit the fixture on its own, with a message saying which cases moved
// and why.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  constellationLayout,
  refineConstellationRoutes,
  type ConstellationLayout,
} from '../../src/derives/cellConstellation.derive';
import {
  CONSTELLATION_EDGE,
  CONSTELLATION_SAFE_TOP,
  constellationMatrixCases,
  constellationMatrixInput,
} from '../fixtures/cellConstellationMatrix';

// jsdom installs its own `URL` global and it does not resolve a relative
// reference against a `file:` base, so the path is joined by hand.
const FIXTURE_PATH = join(
  dirname(fileURLToPath(import.meta.url)), '..', 'fixtures', 'cellConstellationOracle.json',
);
/** The pictures the router found before P2's caps, one hash each. */
const P1_PATH = join(
  dirname(fileURLToPath(import.meta.url)), '..', 'fixtures', 'cellConstellationP1Leaders.json',
);

/** The twelve canonical leaders P2's caps cost, named in the 2026-09-12 ledger.
 * Nine of them come back byte for byte once the refinement has run; the other
 * three cannot, and the reason is recorded beside them below. */
const LOST_AT_P2: readonly string[] = [
  '1440x900@0.22,0.25 n4', '1280x800@0.22,0.75 n4',
  '1920x1080@0.22,0.25 n3 rails', '1920x1080@0.22,0.25 n4 rails',
  '1920x1080@0.78,0.25 n3 rails', '1920x1080@0.78,0.25 n4 rails',
  '1920x920@0.22,0.25 n3 rails', '1920x920@0.22,0.25 n4 rails',
  '1920x920@0.22,0.5 n4 rails', '1920x920@0.78,0.25 n3 rails',
  '1920x920@0.78,0.25 n4 rails', '1920x920@0.78,0.5 n4 rails',
];

/** First paint chose different SEATS for these three than P1 did, and a
 * refinement may not move a seat. Measured 2026-09-12: routing P1's own seats
 * with the `refine` effort reaches all three cleanly, so what stands between
 * them and a clean leader is the candidate the capped router settled on, not
 * the search. That is first paint's business, and P3's. */
const SEATS_MOVED_AT_P2: readonly string[] = [
  '1920x1080@0.22,0.25 n3 rails',
  '1920x1080@0.78,0.25 n3 rails',
  '1920x920@0.22,0.25 n3 rails',
];

interface OraclePoint { x: number; y: number }
interface OracleLabel {
  x: number; y: number; width: number; height: number; inPanel: boolean;
}
interface OracleRoute { points: OraclePoint[]; label: OracleLabel }
interface OraclePlacement {
  slot: string;
  quadrant: string;
  x: number; y: number; width: number; height: number;
  capped: boolean;
  route: OracleRoute | null;
}
interface OracleRect { left: number; top: number; right: number; bottom: number }
interface OracleLayout {
  status: string;
  template: string | null;
  placements: OraclePlacement[];
  masks: OracleRect[];
}
interface OracleInput {
  stageWidth: number; stageHeight: number;
  anchorX: number; anchorY: number;
  panels: number;
  rails: number;
  safeTop: number; edge: number;
  reserved: OracleRect[];
}
interface OracleCase {
  key: string;
  clean: boolean;
  /** Whether the refinement reaches every plate of this case. */
  refinedClean: boolean;
  input: OracleInput;
  layout: OracleLayout;
  /** The same picture after `refineConstellationRoutes` has had its look. It is
   * identical to `layout` wherever first paint was already clean, because a
   * refinement only ever runs behind a fallback leader. */
  refined: OracleLayout;
}
interface OracleFixture { note: string; cases: OracleCase[] }
interface P1Reference {
  note: string;
  reproduced: number;
  moved: number;
  cases: { [key: string]: { sha: string; reproduced: boolean } };
}

const NOTE = 'Generated by __tests__/derives/cellConstellation.oracle.test.ts with '
  + 'CKNERV_CONSTELLATION_ORACLE_WRITE=1. Clean cases are asserted byte for byte; '
  + 'cases marked "clean": false are exempt. "refined" is the same case after the '
  + 'background route refinement, asserted byte for byte wherever it is clean.';

const rect = (box: {
  left: number; top: number; right: number; bottom: number;
}): OracleRect => ({ left: box.left, top: box.top, right: box.right, bottom: box.bottom });

/** Exactly the fields the writer puts on the screen. `route.degraded` and
 * `layout.leaders` are deliberately NOT recorded: they are properties of how
 * the answer was reached, and adding them must not move the picture. */
function projectLayout(layout: ConstellationLayout): OracleLayout {
  return {
    status: layout.status,
    template: layout.template,
    placements: layout.placements.map((placement) => ({
      slot: placement.slot,
      quadrant: placement.quadrant,
      x: placement.x,
      y: placement.y,
      width: placement.width,
      height: placement.height,
      capped: placement.capped,
      route: placement.route
        ? {
          points: placement.route.points.map((point) => ({ x: point.x, y: point.y })),
          label: {
            x: placement.route.label.x,
            y: placement.route.label.y,
            width: placement.route.label.width,
            height: placement.route.label.height,
            inPanel: placement.route.label.inPanel,
          },
        }
        : null,
    })),
    masks: layout.masks.map(rect),
  };
}

/** A case is clean when every instrument it seats is reachable by a route the
 * canonical router itself found. A degraded leader — the straight fallback —
 * is honest, but it is not the picture this oracle is holding still. */
function isClean(layout: ConstellationLayout): boolean {
  return layout.status !== 'unavailable'
    && layout.placements.length > 0
    && layout.placements.every((placement) => placement.route
      && !(placement.route as { degraded?: boolean }).degraded);
}

function buildOracle(): OracleFixture {
  const cases: OracleCase[] = [];
  for (const matrixCase of constellationMatrixCases()) {
    const input = constellationMatrixInput(matrixCase);
    const layout = constellationLayout(input);
    const refined = refineConstellationRoutes(input, layout) ?? layout;
    cases.push({
      key: matrixCase.key,
      clean: isClean(layout),
      refinedClean: isClean(refined),
      input: {
        stageWidth: matrixCase.stageWidth,
        stageHeight: matrixCase.stageHeight,
        anchorX: matrixCase.anchorX,
        anchorY: matrixCase.anchorY,
        panels: matrixCase.count,
        rails: matrixCase.obstacles.length,
        safeTop: CONSTELLATION_SAFE_TOP,
        edge: CONSTELLATION_EDGE,
        reserved: matrixCase.reserved.map(rect),
      },
      layout: projectLayout(layout),
      refined: projectLayout(refined),
    });
  }
  return { note: NOTE, cases };
}

const sha256 = (value: string): string => createHash('sha256').update(value).digest('hex');


const serialize = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`;

describe('the cell constellation oracle', () => {
  it('reproduces every clean layout byte for byte', () => {
    const actual = buildOracle();
    if (process.env.CKNERV_CONSTELLATION_ORACLE_WRITE === '1') {
      writeFileSync(FIXTURE_PATH, serialize(actual));
      // A regeneration run is a write, not a verdict. The assertion below is
      // what the suite means; this branch only refuses to pretend otherwise.
      expect(actual.cases.length).toBeGreaterThan(0);
      return;
    }
    const expected = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8')) as OracleFixture;
    expect(actual.cases.map((item) => item.key)).toEqual(expected.cases.map((item) => item.key));

    const recorded = new Map(expected.cases.map((item) => [item.key, item]));
    let asserted = 0;
    let refinedAsserted = 0;
    for (const item of actual.cases) {
      const oracle = recorded.get(item.key);
      expect(oracle, `no oracle case for ${item.key}`).toBeDefined();
      expect(serialize(item.input), `${item.key}: the inputs themselves moved`)
        .toBe(serialize(oracle!.input));
      // A refinement never runs behind a clean first paint, so a clean case's
      // refined picture IS its first-paint picture, byte for byte.
      if (oracle!.clean) {
        expect(serialize(item.refined), `${item.key}: a refinement moved a clean picture`)
          .toBe(serialize(item.layout));
      }
      if (oracle!.refinedClean) {
        refinedAsserted += 1;
        expect(item.refinedClean, `${item.key}: a refined layout lost a canonical route`)
          .toBe(true);
        expect(serialize(item.refined), `${item.key}: the refined layout moved`)
          .toBe(serialize(oracle!.refined));
      }
      if (!oracle!.clean) continue;
      asserted += 1;
      expect(item.clean, `${item.key}: a clean layout lost a canonical route`).toBe(true);
      expect(serialize(item.layout), `${item.key}: the layout moved`)
        .toBe(serialize(oracle!.layout));
    }
    expect(asserted).toBeGreaterThan(100);
    expect(refinedAsserted).toBeGreaterThan(asserted);
  });

  it('gives back the leaders P2 bought first paint with', () => {
    // Twelve of the 149 layouts the router reached cleanly before P2's caps
    // came back with a dashed fallback instead, ten of them on the 1920-wide
    // desktop stage under the HUD rails. The refinement is the answer to that,
    // and this is the whole of what it recovers: NINE of the twelve, each one
    // byte for byte the picture P1 drew.
    //
    // The other three are not a routing failure. First paint, under its caps,
    // settled on a DIFFERENT candidate than P1 did — the seats moved — and a
    // refinement may not move a seat. Routing P1's own seats with the `refine`
    // effort reaches all three cleanly, which says where the remaining work is:
    // in which candidate first paint keeps, not in how hard it looks for a line.
    const actual = buildOracle();
    const byKey = new Map(actual.cases.map((item) => [item.key, item]));
    const stillDegraded: string[] = [];
    for (const key of LOST_AT_P2) {
      const item = byKey.get(key);
      expect(item, `no oracle case for ${key}`).toBeDefined();
      expect(item!.clean, `${key} is supposed to be one of the twelve`).toBe(false);
      if (!item!.refinedClean) stillDegraded.push(key);
    }
    expect([...stillDegraded].sort()).toEqual([...SEATS_MOVED_AT_P2].sort());

    // And the picture, not merely its cleanliness: every layout P1 routed
    // cleanly that today's first paint plus a refinement reproduces is hashed
    // here, against the P1 fixture at commit 5bb314e5.
    const reference = JSON.parse(readFileSync(P1_PATH, 'utf8')) as P1Reference;
    const moved: string[] = [];
    let reproduced = 0;
    for (const [key, entry] of Object.entries(reference.cases)) {
      const item = byKey.get(key);
      expect(item, `no oracle case for ${key}`).toBeDefined();
      const digest = sha256(serialize(item!.refined));
      if (!entry.reproduced) { moved.push(key); continue; }
      reproduced += 1;
      expect(digest, `${key}: no longer the picture P1 drew`).toBe(entry.sha);
    }
    expect(reproduced).toBe(reference.reproduced);
    expect(moved).toHaveLength(reference.moved);
    expect(reproduced + moved.length).toBe(149);
  });
});
